server:
    port: 8080
    context-path: /
    session:
      timeout: 30
    tomcat:
      uri-encoding: utf-8

logging:
    level:
        root: debug
        gxf.dev.biz.admin: debug
    #当配置了loggin.path属性时，将在该路径下生成spring.log文件，即：此时使用默认的日志文件名spring.log
    #当配置了loggin.file属性时，将在指定路径下生成指定名称的日志文件。默认为项目相对路径，可以为logging.file指定绝对路径。
    #path: /home/gongxufan/logs
    file: admin.log

spring:
    redis:
      host: localhost
      port: 6379
      timeout: 0
      pool:
        max-idle: 8
        max-wait: -1
    datasource:
        url: jdbc:mysql://localhost:3306/admin
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: qwe
        hikari:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
              auto-commit: true

mybatis:
  type-aliases-package: gxf.dev.biz.admin.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: gxf.dev.biz.admin.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count\=countSql

